name: Build & Test

on:
  push:
  pull_request:
  release:
    types: [ published ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build . --tag dmk1111/puppeteer:latest
    - name: Test
      run: |
        cd example
        docker-compose -f docker-compose.integration-tests.yml build tests
        docker-compose -f docker-compose.integration-tests.yml run tests
        ls screenshots/app.png
    - uses: actions/upload-artifact@v3
      with:
        name: test-screenshot.png
        path: example/screenshots/app.png

